version: '3'
services: 
    app_test:
        build: ./app/
        container_name: k8s-desafio-hpa-go-container_test
        stdin_open: true
    app:
        build: .
        container_name: k8s-desafio-hpa-go
        stdin_open: true    