apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-template-label-hpa-desafio
  template:
    metadata:
      labels:
        app: go-template-label-hpa-desafio
    spec:
      containers:
      - name: go-hpa
        image: lealbruno/codeedu-desafio-go-hpa
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
        ports:
        - containerPort: 80